/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_RB_Compte_Client (void);
GtkWidget* create_RL_Admin (void);
GtkWidget* create_AA_Reservation (void);
GtkWidget* create_HS_Agent (void);
GtkWidget* create_Auth (void);
GtkWidget* create_MF_Reclamation (void);
