/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_RB_Compte_Client (void)
{
  GtkWidget *RB_Compte_Client;
  GtkWidget *notebook1;
  GtkWidget *fixed3;
  GtkObject *RB_fact_jour_adj;
  GtkWidget *RB_fact_jour;
  GtkObject *RB_fact_annee_adj;
  GtkWidget *RB_fact_annee;
  GtkObject *RB_fact_mois_adj;
  GtkWidget *RB_fact_mois;
  GtkWidget *RB_ID_facture;
  GtkWidget *RB_montant_total;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *button7;
  GtkWidget *button8;
  GtkWidget *radiobutton2;
  GSList *radiobutton2_group = NULL;
  GtkWidget *radiobutton1;
  GtkWidget *RB_fact_statut;
  GtkWidget *RB_methode_paiement;
  GtkWidget *RB_facture;
  GtkWidget *fixed4;
  GtkWidget *RB_nom_compte;
  GtkWidget *RB_num_telephone;
  GtkWidget *RB_email;
  GtkWidget *RB_mdp;
  GtkWidget *RB_prenom_compte;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *RB_cin_compte;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *RB_notif_mail;
  GtkWidget *RB_confirmer_compte;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label110;
  GtkWidget *RB_Modifier_compte;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label111;
  GtkWidget *RB_supprimer_compte;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label112;
  GtkWidget *RB_cree_compte;
  GtkWidget *fixed5;
  GtkWidget *RB_historique;
  GtkObject *RB_Mois_histo_adj;
  GtkWidget *RB_Mois_histo;
  GtkWidget *label29;
  GtkWidget *RB_label_total;
  GtkWidget *RB_voir_fact;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label113;
  GtkWidget *RB_payer_fact;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label114;
  GtkWidget *label30;
  GtkWidget *fixed6;
  GtkWidget *label31;
  GtkWidget *RB_num_carte;
  GtkWidget *RB_code_carte;
  GtkWidget *label32;
  GtkWidget *label33;

  RB_Compte_Client = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (RB_Compte_Client), _("Compte client"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (RB_Compte_Client), notebook1);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  RB_fact_jour_adj = gtk_adjustment_new (0, 1, 31, 0, 10, 10);
  RB_fact_jour = gtk_spin_button_new (GTK_ADJUSTMENT (RB_fact_jour_adj), 0, 0);
  gtk_widget_show (RB_fact_jour);
  gtk_fixed_put (GTK_FIXED (fixed3), RB_fact_jour, 120, 128);
  gtk_widget_set_size_request (RB_fact_jour, 48, 24);

  RB_fact_annee_adj = gtk_adjustment_new (0, 2000, 2026, 0, 10, 10);
  RB_fact_annee = gtk_spin_button_new (GTK_ADJUSTMENT (RB_fact_annee_adj), 0, 0);
  gtk_widget_show (RB_fact_annee);
  gtk_fixed_put (GTK_FIXED (fixed3), RB_fact_annee, 344, 128);
  gtk_widget_set_size_request (RB_fact_annee, 72, 24);

  RB_fact_mois_adj = gtk_adjustment_new (0, 1, 12, 0, 10, 10);
  RB_fact_mois = gtk_spin_button_new (GTK_ADJUSTMENT (RB_fact_mois_adj), 0, 0);
  gtk_widget_show (RB_fact_mois);
  gtk_fixed_put (GTK_FIXED (fixed3), RB_fact_mois, 224, 128);
  gtk_widget_set_size_request (RB_fact_mois, 48, 24);

  RB_ID_facture = gtk_entry_new ();
  gtk_widget_show (RB_ID_facture);
  gtk_fixed_put (GTK_FIXED (fixed3), RB_ID_facture, 128, 56);
  gtk_widget_set_size_request (RB_ID_facture, 200, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (RB_ID_facture), 8226);

  RB_montant_total = gtk_entry_new ();
  gtk_widget_show (RB_montant_total);
  gtk_fixed_put (GTK_FIXED (fixed3), RB_montant_total, 128, 88);
  gtk_widget_set_size_request (RB_montant_total, 200, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (RB_montant_total), 8226);

  label9 = gtk_label_new (_("Facture"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed3), label9, 176, 0);
  gtk_widget_set_size_request (label9, 144, 48);

  label10 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 272, 120);
  gtk_widget_set_size_request (label10, 72, 40);

  label11 = gtk_label_new (_("Mois"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed3), label11, 160, 120);
  gtk_widget_set_size_request (label11, 80, 40);

  label12 = gtk_label_new (_("jour"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed3), label12, 56, 120);
  gtk_widget_set_size_request (label12, 72, 40);

  label13 = gtk_label_new (_("Date  :"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 0, 120);
  gtk_widget_set_size_request (label13, 72, 40);

  label14 = gtk_label_new (_("Montant total :"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 0, 80);
  gtk_widget_set_size_request (label14, 128, 40);

  label15 = gtk_label_new (_("ID de facture :"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 0, 48);
  gtk_widget_set_size_request (label15, 120, 40);

  label16 = gtk_label_new (_("Statut  :"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 8, 160);
  gtk_widget_set_size_request (label16, 72, 40);

  label17 = gtk_label_new (_("M\303\251thode de paiement  :"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 8, 200);
  gtk_widget_set_size_request (label17, 176, 40);

  button7 = gtk_button_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed3), button7, 32, 256);
  gtk_widget_set_size_request (button7, 104, 45);

  button8 = gtk_button_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed3), button8, 336, 256);
  gtk_widget_set_size_request (button8, 104, 45);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Impay\303\251e"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton2, 160, 160);
  gtk_widget_set_size_request (radiobutton2, 96, 40);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton2), TRUE);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Partiellement pay\303\251e"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton1, 264, 160);
  gtk_widget_set_size_request (radiobutton1, 168, 40);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  RB_fact_statut = gtk_radio_button_new_with_mnemonic (NULL, _("Pay\303\251e"));
  gtk_widget_show (RB_fact_statut);
  gtk_fixed_put (GTK_FIXED (fixed3), RB_fact_statut, 80, 160);
  gtk_widget_set_size_request (RB_fact_statut, 80, 40);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RB_fact_statut), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RB_fact_statut));

  RB_methode_paiement = gtk_combo_box_new_text ();
  gtk_widget_show (RB_methode_paiement);
  gtk_fixed_put (GTK_FIXED (fixed3), RB_methode_paiement, 192, 208);
  gtk_widget_set_size_request (RB_methode_paiement, 33, 31);
  gtk_container_set_border_width (GTK_CONTAINER (RB_methode_paiement), 3);
  gtk_combo_box_append_text (GTK_COMBO_BOX (RB_methode_paiement), _("Carte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (RB_methode_paiement), _("Esp\303\251ce"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (RB_methode_paiement), _("Virement bancaire"));

  RB_facture = gtk_label_new (_("Facture"));
  gtk_widget_show (RB_facture);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), RB_facture);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  RB_nom_compte = gtk_entry_new ();
  gtk_widget_show (RB_nom_compte);
  gtk_fixed_put (GTK_FIXED (fixed4), RB_nom_compte, 216, 48);
  gtk_widget_set_size_request (RB_nom_compte, 216, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (RB_nom_compte), 8226);

  RB_num_telephone = gtk_entry_new ();
  gtk_widget_show (RB_num_telephone);
  gtk_fixed_put (GTK_FIXED (fixed4), RB_num_telephone, 216, 144);
  gtk_widget_set_size_request (RB_num_telephone, 216, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (RB_num_telephone), 8226);

  RB_email = gtk_entry_new ();
  gtk_widget_show (RB_email);
  gtk_fixed_put (GTK_FIXED (fixed4), RB_email, 216, 176);
  gtk_widget_set_size_request (RB_email, 216, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (RB_email), 8226);

  RB_mdp = gtk_entry_new ();
  gtk_widget_show (RB_mdp);
  gtk_fixed_put (GTK_FIXED (fixed4), RB_mdp, 224, 240);
  gtk_widget_set_size_request (RB_mdp, 216, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (RB_mdp), 8226);

  RB_prenom_compte = gtk_entry_new ();
  gtk_widget_show (RB_prenom_compte);
  gtk_fixed_put (GTK_FIXED (fixed4), RB_prenom_compte, 216, 80);
  gtk_widget_set_size_request (RB_prenom_compte, 216, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (RB_prenom_compte), 8226);

  label19 = gtk_label_new (_("Compte"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 152, 8);
  gtk_widget_set_size_request (label19, 192, 40);

  label20 = gtk_label_new (_("Mot de passe :"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 0, 232);
  gtk_widget_set_size_request (label20, 128, 40);

  label21 = gtk_label_new (_("Recevoir des notifications par email :"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed4), label21, 8, 200);
  gtk_widget_set_size_request (label21, 256, 32);

  label22 = gtk_label_new (_("Email :"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed4), label22, 0, 168);
  gtk_widget_set_size_request (label22, 72, 32);

  RB_cin_compte = gtk_entry_new ();
  gtk_widget_show (RB_cin_compte);
  gtk_fixed_put (GTK_FIXED (fixed4), RB_cin_compte, 216, 112);
  gtk_widget_set_size_request (RB_cin_compte, 216, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (RB_cin_compte), 8226);

  label23 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed4), label23, 0, 48);
  gtk_widget_set_size_request (label23, 64, 32);

  label24 = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed4), label24, 8, 80);
  gtk_widget_set_size_request (label24, 72, 32);

  label25 = gtk_label_new (_("CIN :"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed4), label25, 0, 112);
  gtk_widget_set_size_request (label25, 64, 24);

  label26 = gtk_label_new (_("Numero de t\303\251l\303\251phone :"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed4), label26, 8, 136);
  gtk_widget_set_size_request (label26, 168, 32);

  RB_notif_mail = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (RB_notif_mail);
  gtk_fixed_put (GTK_FIXED (fixed4), RB_notif_mail, 272, 200);
  gtk_widget_set_size_request (RB_notif_mail, 72, 32);

  RB_confirmer_compte = gtk_button_new ();
  gtk_widget_show (RB_confirmer_compte);
  gtk_fixed_put (GTK_FIXED (fixed4), RB_confirmer_compte, 16, 280);
  gtk_widget_set_size_request (RB_confirmer_compte, 104, 48);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (RB_confirmer_compte), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label110 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label110);
  gtk_box_pack_start (GTK_BOX (hbox14), label110, FALSE, FALSE, 0);

  RB_Modifier_compte = gtk_button_new ();
  gtk_widget_show (RB_Modifier_compte);
  gtk_fixed_put (GTK_FIXED (fixed4), RB_Modifier_compte, 200, 280);
  gtk_widget_set_size_request (RB_Modifier_compte, 104, 48);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (RB_Modifier_compte), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label111 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label111);
  gtk_box_pack_start (GTK_BOX (hbox15), label111, FALSE, FALSE, 0);

  RB_supprimer_compte = gtk_button_new ();
  gtk_widget_show (RB_supprimer_compte);
  gtk_fixed_put (GTK_FIXED (fixed4), RB_supprimer_compte, 376, 280);
  gtk_widget_set_size_request (RB_supprimer_compte, 104, 48);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (RB_supprimer_compte), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label112 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label112);
  gtk_box_pack_start (GTK_BOX (hbox16), label112, FALSE, FALSE, 0);

  RB_cree_compte = gtk_label_new (_("Creation compte"));
  gtk_widget_show (RB_cree_compte);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), RB_cree_compte);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  RB_historique = gtk_tree_view_new ();
  gtk_widget_show (RB_historique);
  gtk_fixed_put (GTK_FIXED (fixed5), RB_historique, 8, 48);
  gtk_widget_set_size_request (RB_historique, 432, 208);

  RB_Mois_histo_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  RB_Mois_histo = gtk_spin_button_new (GTK_ADJUSTMENT (RB_Mois_histo_adj), 1, 0);
  gtk_widget_show (RB_Mois_histo);
  gtk_fixed_put (GTK_FIXED (fixed5), RB_Mois_histo, 72, 8);
  gtk_widget_set_size_request (RB_Mois_histo, 60, 27);

  label29 = gtk_label_new (_("Mois:"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed5), label29, 8, 16);
  gtk_widget_set_size_request (label29, 41, 17);

  RB_label_total = gtk_label_new (_("Total: 0 TND"));
  gtk_widget_show (RB_label_total);
  gtk_fixed_put (GTK_FIXED (fixed5), RB_label_total, 16, 288);
  gtk_widget_set_size_request (RB_label_total, 111, 17);
  gtk_misc_set_alignment (GTK_MISC (RB_label_total), 0, 0.5);

  RB_voir_fact = gtk_button_new ();
  gtk_widget_show (RB_voir_fact);
  gtk_fixed_put (GTK_FIXED (fixed5), RB_voir_fact, 296, 280);
  gtk_widget_set_size_request (RB_voir_fact, 66, 29);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (RB_voir_fact), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label113 = gtk_label_new_with_mnemonic (_("Voir"));
  gtk_widget_show (label113);
  gtk_box_pack_start (GTK_BOX (hbox17), label113, FALSE, FALSE, 0);

  RB_payer_fact = gtk_button_new ();
  gtk_widget_show (RB_payer_fact);
  gtk_fixed_put (GTK_FIXED (fixed5), RB_payer_fact, 376, 280);
  gtk_widget_set_size_request (RB_payer_fact, 66, 29);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (RB_payer_fact), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label114 = gtk_label_new_with_mnemonic (_("Payer"));
  gtk_widget_show (label114);
  gtk_box_pack_start (GTK_BOX (hbox18), label114, FALSE, FALSE, 0);

  label30 = gtk_label_new (_("Historique facture"));
  gtk_widget_show (label30);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label30);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  label31 = gtk_label_new (_("Num de carte:"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed6), label31, 16, 24);
  gtk_widget_set_size_request (label31, 118, 17);
  gtk_misc_set_alignment (GTK_MISC (label31), 0, 0.5);

  RB_num_carte = gtk_entry_new ();
  gtk_widget_show (RB_num_carte);
  gtk_fixed_put (GTK_FIXED (fixed6), RB_num_carte, 144, 16);
  gtk_widget_set_size_request (RB_num_carte, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (RB_num_carte), 8226);

  RB_code_carte = gtk_entry_new ();
  gtk_widget_show (RB_code_carte);
  gtk_fixed_put (GTK_FIXED (fixed6), RB_code_carte, 144, 56);
  gtk_widget_set_size_request (RB_code_carte, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (RB_code_carte), 8226);

  label32 = gtk_label_new (_("Code de carte:"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed6), label32, 16, 64);
  gtk_widget_set_size_request (label32, 115, 17);
  gtk_misc_set_alignment (GTK_MISC (label32), 0, 0.5);

  label33 = gtk_label_new (_("Paiement par carte"));
  gtk_widget_show (label33);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label33);

  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_RB_annuler_bouton_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_RB_confirmer_bouton_clicked),
                    NULL);
  g_signal_connect ((gpointer) RB_confirmer_compte, "clicked",
                    G_CALLBACK (on_RB_confirmer_bouton_clicked),
                    NULL);
  g_signal_connect ((gpointer) RB_Modifier_compte, "clicked",
                    G_CALLBACK (on_RB_modifier_bouton_clicked),
                    NULL);
  g_signal_connect ((gpointer) RB_supprimer_compte, "clicked",
                    G_CALLBACK (on_RB_supprimer_bouton_clicked),
                    NULL);
  g_signal_connect ((gpointer) RB_Mois_histo, "changed",
                    G_CALLBACK (on_RB_Mois_histo_changed),
                    NULL);
  g_signal_connect ((gpointer) RB_voir_fact, "clicked",
                    G_CALLBACK (on_RB_voir_fact_clicked),
                    NULL);
  g_signal_connect ((gpointer) RB_payer_fact, "clicked",
                    G_CALLBACK (on_RB_payer_fact_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (RB_Compte_Client, RB_Compte_Client, "RB_Compte_Client");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_fact_jour, "RB_fact_jour");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_fact_annee, "RB_fact_annee");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_fact_mois, "RB_fact_mois");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_ID_facture, "RB_ID_facture");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_montant_total, "RB_montant_total");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label9, "label9");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label10, "label10");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label11, "label11");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label12, "label12");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label13, "label13");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label14, "label14");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label15, "label15");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label16, "label16");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label17, "label17");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, button7, "button7");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, button8, "button8");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_fact_statut, "RB_fact_statut");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_methode_paiement, "RB_methode_paiement");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_facture, "RB_facture");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_nom_compte, "RB_nom_compte");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_num_telephone, "RB_num_telephone");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_email, "RB_email");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_mdp, "RB_mdp");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_prenom_compte, "RB_prenom_compte");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label19, "label19");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label20, "label20");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label21, "label21");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label22, "label22");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_cin_compte, "RB_cin_compte");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label23, "label23");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label24, "label24");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label25, "label25");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label26, "label26");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_notif_mail, "RB_notif_mail");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_confirmer_compte, "RB_confirmer_compte");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, image14, "image14");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label110, "label110");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_Modifier_compte, "RB_Modifier_compte");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, image15, "image15");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label111, "label111");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_supprimer_compte, "RB_supprimer_compte");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, image16, "image16");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label112, "label112");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_cree_compte, "RB_cree_compte");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_historique, "RB_historique");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_Mois_histo, "RB_Mois_histo");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label29, "label29");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_label_total, "RB_label_total");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_voir_fact, "RB_voir_fact");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, image17, "image17");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label113, "label113");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_payer_fact, "RB_payer_fact");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, image18, "image18");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label114, "label114");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label30, "label30");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label31, "label31");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_num_carte, "RB_num_carte");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, RB_code_carte, "RB_code_carte");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label32, "label32");
  GLADE_HOOKUP_OBJECT (RB_Compte_Client, label33, "label33");

  return RB_Compte_Client;
}

GtkWidget*
create_RL_Admin (void)
{
  GtkWidget *RL_Admin;
  GtkWidget *notebook2;
  GtkWidget *fixed7;
  GtkWidget *RL_Nom_parking;
  GtkWidget *RL_Address_parking;
  GtkObject *RL_Cap_max_adj;
  GtkWidget *RL_Cap_max;
  GtkWidget *RL_Horaire_overture;
  GtkObject *RL_Nb_place_adj;
  GtkWidget *RL_Nb_place;
  GtkWidget *RL_Tarif_horaire;
  GtkWidget *RL_ID_parking;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkWidget *label40;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkWidget *label43;
  GtkWidget *combo1;
  GtkWidget *RL_Agent_affecte;
  GtkWidget *button14;
  GtkWidget *button15;
  GtkWidget *RL_Type_parking;
  GtkWidget *RL_Service_recharge;
  GtkWidget *RL_service_surveillance;
  GtkWidget *RL_Access_handicape;
  GtkWidget *RL_service_abri_velo;
  GtkWidget *label44;
  GtkWidget *fixed8;
  GtkWidget *cellview1;
  GtkWidget *hbuttonbox1;
  GtkWidget *RL_parking_tree;
  GtkWidget *RL_ajouter_parking;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label45;
  GtkWidget *RL_modifier_parking;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label47;
  GtkWidget *RL_supprimer_parking;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label46;
  GtkWidget *label48;
  GtkWidget *fixed9;
  GtkWidget *RL_list_agent;
  GtkWidget *label49;
  GtkWidget *label50;
  GtkWidget *label51;
  GtkWidget *RL_agent_sans_parking;
  GtkWidget *RL_agent_annuler;
  GtkWidget *RL_agent_affecter;
  GtkWidget *label52;

  RL_Admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (RL_Admin), _("Admin"));

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_container_add (GTK_CONTAINER (RL_Admin), notebook2);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed7);

  RL_Nom_parking = gtk_entry_new ();
  gtk_widget_show (RL_Nom_parking);
  gtk_fixed_put (GTK_FIXED (fixed7), RL_Nom_parking, 240, 56);
  gtk_widget_set_size_request (RL_Nom_parking, 164, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (RL_Nom_parking), 8226);

  RL_Address_parking = gtk_entry_new ();
  gtk_widget_show (RL_Address_parking);
  gtk_fixed_put (GTK_FIXED (fixed7), RL_Address_parking, 240, 96);
  gtk_widget_set_size_request (RL_Address_parking, 164, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (RL_Address_parking), 8226);

  RL_Cap_max_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  RL_Cap_max = gtk_spin_button_new (GTK_ADJUSTMENT (RL_Cap_max_adj), 1, 0);
  gtk_widget_show (RL_Cap_max);
  gtk_fixed_put (GTK_FIXED (fixed7), RL_Cap_max, 240, 144);
  gtk_widget_set_size_request (RL_Cap_max, 164, 27);

  RL_Horaire_overture = gtk_entry_new ();
  gtk_widget_show (RL_Horaire_overture);
  gtk_fixed_put (GTK_FIXED (fixed7), RL_Horaire_overture, 240, 384);
  gtk_widget_set_size_request (RL_Horaire_overture, 164, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (RL_Horaire_overture), 8226);

  RL_Nb_place_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  RL_Nb_place = gtk_spin_button_new (GTK_ADJUSTMENT (RL_Nb_place_adj), 1, 0);
  gtk_widget_show (RL_Nb_place);
  gtk_fixed_put (GTK_FIXED (fixed7), RL_Nb_place, 240, 288);
  gtk_widget_set_size_request (RL_Nb_place, 164, 27);

  RL_Tarif_horaire = gtk_entry_new ();
  gtk_widget_show (RL_Tarif_horaire);
  gtk_fixed_put (GTK_FIXED (fixed7), RL_Tarif_horaire, 240, 240);
  gtk_widget_set_size_request (RL_Tarif_horaire, 164, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (RL_Tarif_horaire), 8226);

  RL_ID_parking = gtk_entry_new ();
  gtk_widget_show (RL_ID_parking);
  gtk_fixed_put (GTK_FIXED (fixed7), RL_ID_parking, 240, 16);
  gtk_widget_set_size_request (RL_ID_parking, 164, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (RL_ID_parking), 8226);

  label34 = gtk_label_new (_("ID_Parking :"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed7), label34, 24, 16);
  gtk_widget_set_size_request (label34, 102, 17);
  gtk_misc_set_alignment (GTK_MISC (label34), 0, 0.5);

  label35 = gtk_label_new (_("Nom du Parking : \n"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed7), label35, 24, 56);
  gtk_widget_set_size_request (label35, 126, 25);
  gtk_label_set_justify (GTK_LABEL (label35), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label35), 0, 0.5);

  label36 = gtk_label_new (_("Adresse :"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed7), label36, 24, 96);
  gtk_widget_set_size_request (label36, 118, 25);
  gtk_misc_set_alignment (GTK_MISC (label36), 0, 0.5);

  label37 = gtk_label_new (_("Capacit\303\251 maximale : "));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed7), label37, 24, 144);
  gtk_widget_set_size_request (label37, 136, 25);
  gtk_misc_set_alignment (GTK_MISC (label37), 0, 0.5);

  label38 = gtk_label_new (_("Type de Parking : "));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed7), label38, 24, 192);
  gtk_widget_set_size_request (label38, 126, 25);
  gtk_misc_set_alignment (GTK_MISC (label38), 0, 0.5);

  label39 = gtk_label_new (_("Tarif Horaire : "));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed7), label39, 24, 240);
  gtk_widget_set_size_request (label39, 99, 25);
  gtk_misc_set_alignment (GTK_MISC (label39), 0, 0.5);

  label40 = gtk_label_new (_("Nombre de place disponible : "));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed7), label40, 24, 288);
  gtk_widget_set_size_request (label40, 199, 25);
  gtk_misc_set_alignment (GTK_MISC (label40), 0, 0.5);

  label41 = gtk_label_new (_("Services Offerts :"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed7), label41, 24, 336);
  gtk_widget_set_size_request (label41, 129, 25);
  gtk_misc_set_alignment (GTK_MISC (label41), 0, 0.5);

  label42 = gtk_label_new (_("Horaires d'Ouverture :"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed7), label42, 24, 384);
  gtk_widget_set_size_request (label42, 159, 25);
  gtk_misc_set_alignment (GTK_MISC (label42), 0, 0.5);

  label43 = gtk_label_new (_("Agent Affect\303\251 : "));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed7), label43, 24, 432);
  gtk_widget_set_size_request (label43, 124, 25);
  gtk_misc_set_alignment (GTK_MISC (label43), 0, 0.5);

  combo1 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo1)->popwin),
                     "GladeParentKey", combo1);
  gtk_widget_show (combo1);
  gtk_fixed_put (GTK_FIXED (fixed7), combo1, 240, 432);
  gtk_widget_set_size_request (combo1, 164, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo1), TRUE);

  RL_Agent_affecte = GTK_COMBO (combo1)->entry;
  gtk_widget_show (RL_Agent_affecte);
  gtk_entry_set_invisible_char (GTK_ENTRY (RL_Agent_affecte), 8226);

  button14 = gtk_button_new_with_mnemonic (_("Comfirmer"));
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed7), button14, 648, 528);
  gtk_widget_set_size_request (button14, 86, 29);

  button15 = gtk_button_new_with_mnemonic (_("R\303\251initialiser"));
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed7), button15, 552, 528);
  gtk_widget_set_size_request (button15, 94, 29);

  RL_Type_parking = gtk_combo_box_entry_new_text ();
  gtk_widget_show (RL_Type_parking);
  gtk_fixed_put (GTK_FIXED (fixed7), RL_Type_parking, 240, 192);
  gtk_widget_set_size_request (RL_Type_parking, 164, 27);
  gtk_combo_box_append_text (GTK_COMBO_BOX (RL_Type_parking), _("Couverte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (RL_Type_parking), _("Sous-sol"));

  RL_Service_recharge = gtk_check_button_new_with_mnemonic (_("Borne de recharge"));
  gtk_widget_show (RL_Service_recharge);
  gtk_fixed_put (GTK_FIXED (fixed7), RL_Service_recharge, 240, 336);
  gtk_widget_set_size_request (RL_Service_recharge, 155, 24);

  RL_service_surveillance = gtk_check_button_new_with_mnemonic (_("Vid\303\251o surveillance"));
  gtk_widget_show (RL_service_surveillance);
  gtk_fixed_put (GTK_FIXED (fixed7), RL_service_surveillance, 400, 336);
  gtk_widget_set_size_request (RL_service_surveillance, 152, 24);

  RL_Access_handicape = gtk_check_button_new_with_mnemonic (_("Acc\303\250s handicap\303\251s"));
  gtk_widget_show (RL_Access_handicape);
  gtk_fixed_put (GTK_FIXED (fixed7), RL_Access_handicape, 560, 336);
  gtk_widget_set_size_request (RL_Access_handicape, 151, 24);

  RL_service_abri_velo = gtk_check_button_new_with_mnemonic (_("Abri V\303\251lo"));
  gtk_widget_show (RL_service_abri_velo);
  gtk_fixed_put (GTK_FIXED (fixed7), RL_service_abri_velo, 712, 336);
  gtk_widget_set_size_request (RL_service_abri_velo, 118, 24);

  label44 = gtk_label_new (_("Ajouter parking"));
  gtk_widget_show (label44);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label44);
  gtk_widget_set_size_request (label44, 125, -1);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed8);

  cellview1 = gtk_cell_view_new ();
  gtk_widget_show (cellview1);
  gtk_fixed_put (GTK_FIXED (fixed8), cellview1, 384, 264);
  gtk_widget_set_size_request (cellview1, 50, 50);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_fixed_put (GTK_FIXED (fixed8), hbuttonbox1, 680, 392);
  gtk_widget_set_size_request (hbuttonbox1, 170, 29);

  RL_parking_tree = gtk_tree_view_new ();
  gtk_widget_show (RL_parking_tree);
  gtk_fixed_put (GTK_FIXED (fixed8), RL_parking_tree, 16, 80);
  gtk_widget_set_size_request (RL_parking_tree, 640, 208);

  RL_ajouter_parking = gtk_button_new ();
  gtk_widget_show (RL_ajouter_parking);
  gtk_fixed_put (GTK_FIXED (fixed8), RL_ajouter_parking, 520, 40);
  gtk_widget_set_size_request (RL_ajouter_parking, 136, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (RL_ajouter_parking), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("Ajouter parking"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox1), label45, FALSE, FALSE, 0);

  RL_modifier_parking = gtk_button_new ();
  gtk_widget_show (RL_modifier_parking);
  gtk_fixed_put (GTK_FIXED (fixed8), RL_modifier_parking, 424, 296);
  gtk_widget_set_size_request (RL_modifier_parking, 112, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (RL_modifier_parking), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox3), label47, FALSE, FALSE, 0);

  RL_supprimer_parking = gtk_button_new ();
  gtk_widget_show (RL_supprimer_parking);
  gtk_fixed_put (GTK_FIXED (fixed8), RL_supprimer_parking, 544, 296);
  gtk_widget_set_size_request (RL_supprimer_parking, 112, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (RL_supprimer_parking), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox2), label46, FALSE, FALSE, 0);

  label48 = gtk_label_new (_("Gestion des parkings"));
  gtk_widget_show (label48);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label48);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed9);

  RL_list_agent = gtk_tree_view_new ();
  gtk_widget_show (RL_list_agent);
  gtk_fixed_put (GTK_FIXED (fixed9), RL_list_agent, 24, 120);
  gtk_widget_set_size_request (RL_list_agent, 304, 232);

  label49 = gtk_label_new (_("Affecter un agent \303\240 un parking"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed9), label49, 288, 16);
  gtk_widget_set_size_request (label49, 248, 48);

  label50 = gtk_label_new (_("Liste des agents non affect\303\251s"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed9), label50, 64, 96);
  gtk_widget_set_size_request (label50, 213, 17);

  label51 = gtk_label_new (_("Parking sans agent :"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed9), label51, 376, 112);
  gtk_widget_set_size_request (label51, 144, 40);

  RL_agent_sans_parking = gtk_combo_box_entry_new_text ();
  gtk_widget_show (RL_agent_sans_parking);
  gtk_fixed_put (GTK_FIXED (fixed9), RL_agent_sans_parking, 536, 112);
  gtk_widget_set_size_request (RL_agent_sans_parking, 181, 36);

  RL_agent_annuler = gtk_button_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (RL_agent_annuler);
  gtk_fixed_put (GTK_FIXED (fixed9), RL_agent_annuler, 520, 328);
  gtk_widget_set_size_request (RL_agent_annuler, 130, 29);

  RL_agent_affecter = gtk_button_new_with_mnemonic (_("Affecter"));
  gtk_widget_show (RL_agent_affecter);
  gtk_fixed_put (GTK_FIXED (fixed9), RL_agent_affecter, 664, 328);
  gtk_widget_set_size_request (RL_agent_affecter, 130, 29);

  label52 = gtk_label_new (_("Calcul"));
  gtk_widget_show (label52);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label52);
  gtk_widget_set_size_request (label52, 70, -1);

  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_RL_buttonCO_clicked),
                    NULL);
  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_RL_BCom_clicked),
                    NULL);
  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (on_RL_buttonR_clicked),
                    NULL);
  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (on_RL_BR___clicked),
                    NULL);
  g_signal_connect ((gpointer) RL_ajouter_parking, "clicked",
                    G_CALLBACK (on_RL_buttonAdd_clicked),
                    NULL);
  g_signal_connect ((gpointer) RL_modifier_parking, "clicked",
                    G_CALLBACK (on_RL_buttonMod_clicked),
                    NULL);
  g_signal_connect ((gpointer) RL_supprimer_parking, "clicked",
                    G_CALLBACK (on_Rl_buttonSupp_clicked),
                    NULL);
  g_signal_connect ((gpointer) RL_agent_annuler, "clicked",
                    G_CALLBACK (on_RL_Annuler_clicked),
                    NULL);
  g_signal_connect ((gpointer) RL_agent_affecter, "clicked",
                    G_CALLBACK (on_RL_Affecter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (RL_Admin, RL_Admin, "RL_Admin");
  GLADE_HOOKUP_OBJECT (RL_Admin, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (RL_Admin, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (RL_Admin, RL_Nom_parking, "RL_Nom_parking");
  GLADE_HOOKUP_OBJECT (RL_Admin, RL_Address_parking, "RL_Address_parking");
  GLADE_HOOKUP_OBJECT (RL_Admin, RL_Cap_max, "RL_Cap_max");
  GLADE_HOOKUP_OBJECT (RL_Admin, RL_Horaire_overture, "RL_Horaire_overture");
  GLADE_HOOKUP_OBJECT (RL_Admin, RL_Nb_place, "RL_Nb_place");
  GLADE_HOOKUP_OBJECT (RL_Admin, RL_Tarif_horaire, "RL_Tarif_horaire");
  GLADE_HOOKUP_OBJECT (RL_Admin, RL_ID_parking, "RL_ID_parking");
  GLADE_HOOKUP_OBJECT (RL_Admin, label34, "label34");
  GLADE_HOOKUP_OBJECT (RL_Admin, label35, "label35");
  GLADE_HOOKUP_OBJECT (RL_Admin, label36, "label36");
  GLADE_HOOKUP_OBJECT (RL_Admin, label37, "label37");
  GLADE_HOOKUP_OBJECT (RL_Admin, label38, "label38");
  GLADE_HOOKUP_OBJECT (RL_Admin, label39, "label39");
  GLADE_HOOKUP_OBJECT (RL_Admin, label40, "label40");
  GLADE_HOOKUP_OBJECT (RL_Admin, label41, "label41");
  GLADE_HOOKUP_OBJECT (RL_Admin, label42, "label42");
  GLADE_HOOKUP_OBJECT (RL_Admin, label43, "label43");
  GLADE_HOOKUP_OBJECT (RL_Admin, combo1, "combo1");
  GLADE_HOOKUP_OBJECT (RL_Admin, RL_Agent_affecte, "RL_Agent_affecte");
  GLADE_HOOKUP_OBJECT (RL_Admin, button14, "button14");
  GLADE_HOOKUP_OBJECT (RL_Admin, button15, "button15");
  GLADE_HOOKUP_OBJECT (RL_Admin, RL_Type_parking, "RL_Type_parking");
  GLADE_HOOKUP_OBJECT (RL_Admin, RL_Service_recharge, "RL_Service_recharge");
  GLADE_HOOKUP_OBJECT (RL_Admin, RL_service_surveillance, "RL_service_surveillance");
  GLADE_HOOKUP_OBJECT (RL_Admin, RL_Access_handicape, "RL_Access_handicape");
  GLADE_HOOKUP_OBJECT (RL_Admin, RL_service_abri_velo, "RL_service_abri_velo");
  GLADE_HOOKUP_OBJECT (RL_Admin, label44, "label44");
  GLADE_HOOKUP_OBJECT (RL_Admin, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (RL_Admin, cellview1, "cellview1");
  GLADE_HOOKUP_OBJECT (RL_Admin, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (RL_Admin, RL_parking_tree, "RL_parking_tree");
  GLADE_HOOKUP_OBJECT (RL_Admin, RL_ajouter_parking, "RL_ajouter_parking");
  GLADE_HOOKUP_OBJECT (RL_Admin, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (RL_Admin, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (RL_Admin, image1, "image1");
  GLADE_HOOKUP_OBJECT (RL_Admin, label45, "label45");
  GLADE_HOOKUP_OBJECT (RL_Admin, RL_modifier_parking, "RL_modifier_parking");
  GLADE_HOOKUP_OBJECT (RL_Admin, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (RL_Admin, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (RL_Admin, image3, "image3");
  GLADE_HOOKUP_OBJECT (RL_Admin, label47, "label47");
  GLADE_HOOKUP_OBJECT (RL_Admin, RL_supprimer_parking, "RL_supprimer_parking");
  GLADE_HOOKUP_OBJECT (RL_Admin, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (RL_Admin, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (RL_Admin, image2, "image2");
  GLADE_HOOKUP_OBJECT (RL_Admin, label46, "label46");
  GLADE_HOOKUP_OBJECT (RL_Admin, label48, "label48");
  GLADE_HOOKUP_OBJECT (RL_Admin, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (RL_Admin, RL_list_agent, "RL_list_agent");
  GLADE_HOOKUP_OBJECT (RL_Admin, label49, "label49");
  GLADE_HOOKUP_OBJECT (RL_Admin, label50, "label50");
  GLADE_HOOKUP_OBJECT (RL_Admin, label51, "label51");
  GLADE_HOOKUP_OBJECT (RL_Admin, RL_agent_sans_parking, "RL_agent_sans_parking");
  GLADE_HOOKUP_OBJECT (RL_Admin, RL_agent_annuler, "RL_agent_annuler");
  GLADE_HOOKUP_OBJECT (RL_Admin, RL_agent_affecter, "RL_agent_affecter");
  GLADE_HOOKUP_OBJECT (RL_Admin, label52, "label52");

  return RL_Admin;
}

GtkWidget*
create_AA_Reservation (void)
{
  GtkWidget *AA_Reservation;
  GtkWidget *notebook3;
  GtkWidget *fixed10;
  GtkWidget *AA_nom;
  GtkWidget *AA_matricule;
  GtkWidget *label53;
  GtkObject *AA_arriver_jour_adj;
  GtkWidget *AA_arriver_jour;
  GtkWidget *label54;
  GtkWidget *label55;
  GtkWidget *label56;
  GtkObject *AA_arriver_heure_adj;
  GtkWidget *AA_arriver_heure;
  GtkObject *AA_arriver_min_adj;
  GtkWidget *AA_arriver_min;
  GtkWidget *label57;
  GtkWidget *label58;
  GtkObject *AA_depart_jour_adj;
  GtkWidget *AA_depart_jour;
  GtkWidget *label59;
  GtkWidget *label60;
  GtkObject *AA_depart_mois_adj;
  GtkWidget *AA_depart_mois;
  GtkWidget *label61;
  GtkObject *AA_depart_heure_adj;
  GtkWidget *AA_depart_heure;
  GtkObject *AA_depart_min_adj;
  GtkWidget *AA_depart_min;
  GtkWidget *label62;
  GtkWidget *label63;
  GtkObject *AA_arriver_mois_adj;
  GtkWidget *AA_arriver_mois;
  GtkWidget *AA_Ajouter;
  GtkWidget *AA_modifier;
  GtkWidget *AA_supprimer;
  GtkWidget *label64;
  GtkWidget *fixed11;
  GtkWidget *vbuttonbox1;
  GtkWidget *table1;
  GtkWidget *label66;
  GtkWidget *AA_Place_dispo_label;
  GtkWidget *AA_select;
  GtkWidget *AA_Place_modifier;
  GtkWidget *AA_place_confirmer;
  GtkWidget *AA_enregister;
  GtkWidget *AA_Place_supprimer;
  GtkWidget *label67;

  AA_Reservation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (AA_Reservation), _("Reservation"));

  notebook3 = gtk_notebook_new ();
  gtk_widget_show (notebook3);
  gtk_container_add (GTK_CONTAINER (AA_Reservation), notebook3);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed10);

  AA_nom = gtk_entry_new ();
  gtk_widget_show (AA_nom);
  gtk_fixed_put (GTK_FIXED (fixed10), AA_nom, 360, 104);
  gtk_widget_set_size_request (AA_nom, 336, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (AA_nom), 8226);

  AA_matricule = gtk_entry_new ();
  gtk_widget_show (AA_matricule);
  gtk_fixed_put (GTK_FIXED (fixed10), AA_matricule, 360, 192);
  gtk_widget_set_size_request (AA_matricule, 336, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (AA_matricule), 8226);

  label53 = gtk_label_new_with_mnemonic (_("RESERVATION"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed10), label53, 232, 8);
  gtk_widget_set_size_request (label53, 448, 64);
  gtk_label_set_justify (GTK_LABEL (label53), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label53), 0.49, 0.5);

  AA_arriver_jour_adj = gtk_adjustment_new (0, 0, 30, 0, 10, 10);
  AA_arriver_jour = gtk_spin_button_new (GTK_ADJUSTMENT (AA_arriver_jour_adj), 1, 0);
  gtk_widget_show (AA_arriver_jour);
  gtk_fixed_put (GTK_FIXED (fixed10), AA_arriver_jour, 336, 312);
  gtk_widget_set_size_request (AA_arriver_jour, 60, 27);

  label54 = gtk_label_new (_("Date et Heure d'arriv\303\251e:"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed10), label54, 8, 312);
  gtk_widget_set_size_request (label54, 224, 24);

  label55 = gtk_label_new (_("Nom et Pr\303\251nom:"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed10), label55, 8, 104);
  gtk_widget_set_size_request (label55, 176, 32);

  label56 = gtk_label_new (_("heure"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed10), label56, 592, 312);
  gtk_widget_set_size_request (label56, 72, 32);

  AA_arriver_heure_adj = gtk_adjustment_new (0, 0, 24, 1, 10, 10);
  AA_arriver_heure = gtk_spin_button_new (GTK_ADJUSTMENT (AA_arriver_heure_adj), 1, 0);
  gtk_widget_show (AA_arriver_heure);
  gtk_fixed_put (GTK_FIXED (fixed10), AA_arriver_heure, 688, 312);
  gtk_widget_set_size_request (AA_arriver_heure, 60, 27);

  AA_arriver_min_adj = gtk_adjustment_new (0, 0, 60, 1, 10, 10);
  AA_arriver_min = gtk_spin_button_new (GTK_ADJUSTMENT (AA_arriver_min_adj), 1, 0);
  gtk_widget_show (AA_arriver_min);
  gtk_fixed_put (GTK_FIXED (fixed10), AA_arriver_min, 752, 312);
  gtk_widget_set_size_request (AA_arriver_min, 60, 27);

  label57 = gtk_label_new (_("Date et heure de d\303\251part:"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed10), label57, 16, 400);
  gtk_widget_set_size_request (label57, 216, 32);

  label58 = gtk_label_new (_("jour"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed10), label58, 256, 408);
  gtk_widget_set_size_request (label58, 49, 17);

  AA_depart_jour_adj = gtk_adjustment_new (0, 0, 30, 1, 10, 10);
  AA_depart_jour = gtk_spin_button_new (GTK_ADJUSTMENT (AA_depart_jour_adj), 1, 0);
  gtk_widget_show (AA_depart_jour);
  gtk_fixed_put (GTK_FIXED (fixed10), AA_depart_jour, 336, 400);
  gtk_widget_set_size_request (AA_depart_jour, 60, 27);

  label59 = gtk_label_new (_("mois"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed10), label59, 416, 312);
  gtk_widget_set_size_request (label59, 64, 32);

  label60 = gtk_label_new (_("mois"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed10), label60, 424, 408);
  gtk_widget_set_size_request (label60, 49, 17);

  AA_depart_mois_adj = gtk_adjustment_new (0, 0, 12, 1, 10, 10);
  AA_depart_mois = gtk_spin_button_new (GTK_ADJUSTMENT (AA_depart_mois_adj), 1, 0);
  gtk_widget_show (AA_depart_mois);
  gtk_fixed_put (GTK_FIXED (fixed10), AA_depart_mois, 488, 400);
  gtk_widget_set_size_request (AA_depart_mois, 60, 27);

  label61 = gtk_label_new (_("heure"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed10), label61, 608, 408);
  gtk_widget_set_size_request (label61, 49, 17);

  AA_depart_heure_adj = gtk_adjustment_new (0, 0, 24, 1, 10, 10);
  AA_depart_heure = gtk_spin_button_new (GTK_ADJUSTMENT (AA_depart_heure_adj), 1, 0);
  gtk_widget_show (AA_depart_heure);
  gtk_fixed_put (GTK_FIXED (fixed10), AA_depart_heure, 688, 400);
  gtk_widget_set_size_request (AA_depart_heure, 60, 27);

  AA_depart_min_adj = gtk_adjustment_new (0, 0, 60, 1, 10, 10);
  AA_depart_min = gtk_spin_button_new (GTK_ADJUSTMENT (AA_depart_min_adj), 1, 0);
  gtk_widget_show (AA_depart_min);
  gtk_fixed_put (GTK_FIXED (fixed10), AA_depart_min, 752, 400);
  gtk_widget_set_size_request (AA_depart_min, 60, 27);

  label62 = gtk_label_new (_("jour"));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed10), label62, 248, 312);
  gtk_widget_set_size_request (label62, 64, 32);

  label63 = gtk_label_new (_("Num\303\251ro de plaque d'immatriculation:"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed10), label63, 16, 192);
  gtk_widget_set_size_request (label63, 304, 40);

  AA_arriver_mois_adj = gtk_adjustment_new (0, 0, 30, 0, 10, 10);
  AA_arriver_mois = gtk_spin_button_new (GTK_ADJUSTMENT (AA_arriver_mois_adj), 1, 0);
  gtk_widget_show (AA_arriver_mois);
  gtk_fixed_put (GTK_FIXED (fixed10), AA_arriver_mois, 488, 312);
  gtk_widget_set_size_request (AA_arriver_mois, 60, 27);

  AA_Ajouter = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (AA_Ajouter);
  gtk_fixed_put (GTK_FIXED (fixed10), AA_Ajouter, 448, 584);
  gtk_widget_set_size_request (AA_Ajouter, 136, 40);

  AA_modifier = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (AA_modifier);
  gtk_fixed_put (GTK_FIXED (fixed10), AA_modifier, 600, 584);
  gtk_widget_set_size_request (AA_modifier, 136, 40);

  AA_supprimer = gtk_button_new_with_mnemonic (_("supprimer "));
  gtk_widget_show (AA_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed10), AA_supprimer, 752, 584);
  gtk_widget_set_size_request (AA_supprimer, 136, 40);

  label64 = gtk_label_new (_("reservation1"));
  gtk_widget_show (label64);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 0), label64);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed11);

  vbuttonbox1 = gtk_vbutton_box_new ();
  gtk_widget_show (vbuttonbox1);
  gtk_fixed_put (GTK_FIXED (fixed11), vbuttonbox1, 232, 288);
  gtk_widget_set_size_request (vbuttonbox1, 85, 87);

  table1 = gtk_table_new (10, 30, FALSE);
  gtk_widget_show (table1);
  gtk_fixed_put (GTK_FIXED (fixed11), table1, 376, 136);
  gtk_widget_set_size_request (table1, 300, 160);

  label66 = gtk_label_new (_("R\303\251servation"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed11), label66, 280, 24);
  gtk_widget_set_size_request (label66, 320, 56);

  AA_Place_dispo_label = gtk_label_new (_("Les places disponibles"));
  gtk_widget_show (AA_Place_dispo_label);
  gtk_fixed_put (GTK_FIXED (fixed11), AA_Place_dispo_label, 96, 168);
  gtk_widget_set_size_request (AA_Place_dispo_label, 256, 48);

  AA_select = gtk_button_new_with_mnemonic (_("S\303\251lectionner"));
  gtk_widget_show (AA_select);
  gtk_fixed_put (GTK_FIXED (fixed11), AA_select, 152, 256);
  gtk_widget_set_size_request (AA_select, 144, 40);

  AA_Place_modifier = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (AA_Place_modifier);
  gtk_fixed_put (GTK_FIXED (fixed11), AA_Place_modifier, 48, 328);
  gtk_widget_set_size_request (AA_Place_modifier, 144, 40);

  AA_place_confirmer = gtk_button_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (AA_place_confirmer);
  gtk_fixed_put (GTK_FIXED (fixed11), AA_place_confirmer, 232, 328);
  gtk_widget_set_size_request (AA_place_confirmer, 144, 40);

  AA_enregister = gtk_button_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (AA_enregister);
  gtk_fixed_put (GTK_FIXED (fixed11), AA_enregister, 536, 440);
  gtk_widget_set_size_request (AA_enregister, 144, 40);

  AA_Place_supprimer = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (AA_Place_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed11), AA_Place_supprimer, 720, 440);
  gtk_widget_set_size_request (AA_Place_supprimer, 144, 40);

  label67 = gtk_label_new (_("parking"));
  gtk_widget_show (label67);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 1), label67);

  g_signal_connect ((gpointer) AA_Ajouter, "clicked",
                    G_CALLBACK (on_AA_Ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) AA_modifier, "clicked",
                    G_CALLBACK (on_AA_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) AA_supprimer, "clicked",
                    G_CALLBACK (on_AA_supprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (AA_Reservation, AA_Reservation, "AA_Reservation");
  GLADE_HOOKUP_OBJECT (AA_Reservation, notebook3, "notebook3");
  GLADE_HOOKUP_OBJECT (AA_Reservation, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (AA_Reservation, AA_nom, "AA_nom");
  GLADE_HOOKUP_OBJECT (AA_Reservation, AA_matricule, "AA_matricule");
  GLADE_HOOKUP_OBJECT (AA_Reservation, label53, "label53");
  GLADE_HOOKUP_OBJECT (AA_Reservation, AA_arriver_jour, "AA_arriver_jour");
  GLADE_HOOKUP_OBJECT (AA_Reservation, label54, "label54");
  GLADE_HOOKUP_OBJECT (AA_Reservation, label55, "label55");
  GLADE_HOOKUP_OBJECT (AA_Reservation, label56, "label56");
  GLADE_HOOKUP_OBJECT (AA_Reservation, AA_arriver_heure, "AA_arriver_heure");
  GLADE_HOOKUP_OBJECT (AA_Reservation, AA_arriver_min, "AA_arriver_min");
  GLADE_HOOKUP_OBJECT (AA_Reservation, label57, "label57");
  GLADE_HOOKUP_OBJECT (AA_Reservation, label58, "label58");
  GLADE_HOOKUP_OBJECT (AA_Reservation, AA_depart_jour, "AA_depart_jour");
  GLADE_HOOKUP_OBJECT (AA_Reservation, label59, "label59");
  GLADE_HOOKUP_OBJECT (AA_Reservation, label60, "label60");
  GLADE_HOOKUP_OBJECT (AA_Reservation, AA_depart_mois, "AA_depart_mois");
  GLADE_HOOKUP_OBJECT (AA_Reservation, label61, "label61");
  GLADE_HOOKUP_OBJECT (AA_Reservation, AA_depart_heure, "AA_depart_heure");
  GLADE_HOOKUP_OBJECT (AA_Reservation, AA_depart_min, "AA_depart_min");
  GLADE_HOOKUP_OBJECT (AA_Reservation, label62, "label62");
  GLADE_HOOKUP_OBJECT (AA_Reservation, label63, "label63");
  GLADE_HOOKUP_OBJECT (AA_Reservation, AA_arriver_mois, "AA_arriver_mois");
  GLADE_HOOKUP_OBJECT (AA_Reservation, AA_Ajouter, "AA_Ajouter");
  GLADE_HOOKUP_OBJECT (AA_Reservation, AA_modifier, "AA_modifier");
  GLADE_HOOKUP_OBJECT (AA_Reservation, AA_supprimer, "AA_supprimer");
  GLADE_HOOKUP_OBJECT (AA_Reservation, label64, "label64");
  GLADE_HOOKUP_OBJECT (AA_Reservation, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (AA_Reservation, vbuttonbox1, "vbuttonbox1");
  GLADE_HOOKUP_OBJECT (AA_Reservation, table1, "table1");
  GLADE_HOOKUP_OBJECT (AA_Reservation, label66, "label66");
  GLADE_HOOKUP_OBJECT (AA_Reservation, AA_Place_dispo_label, "AA_Place_dispo_label");
  GLADE_HOOKUP_OBJECT (AA_Reservation, AA_select, "AA_select");
  GLADE_HOOKUP_OBJECT (AA_Reservation, AA_Place_modifier, "AA_Place_modifier");
  GLADE_HOOKUP_OBJECT (AA_Reservation, AA_place_confirmer, "AA_place_confirmer");
  GLADE_HOOKUP_OBJECT (AA_Reservation, AA_enregister, "AA_enregister");
  GLADE_HOOKUP_OBJECT (AA_Reservation, AA_Place_supprimer, "AA_Place_supprimer");
  GLADE_HOOKUP_OBJECT (AA_Reservation, label67, "label67");

  return AA_Reservation;
}

GtkWidget*
create_HS_Agent (void)
{
  GtkWidget *HS_Agent;
  GtkWidget *notebook4;
  GtkWidget *fixed12;
  GtkWidget *HS_lst_agent;
  GtkWidget *label73;
  GtkWidget *HS_bt_ajout;
  GtkWidget *HS_bt_suprimer;
  GtkWidget *HS_filter_affecte;
  GtkWidget *HS_filter_non_affecte;
  GtkWidget *HS_bt_status;
  GtkWidget *label69;
  GtkWidget *fixed13;
  GtkWidget *label74;
  GtkWidget *label75;
  GtkWidget *HS_cin;
  GtkWidget *HS_nom;
  GtkWidget *label76;
  GtkWidget *label79;
  GtkWidget *label78;
  GtkWidget *label77;
  GtkWidget *HS_prenom;
  GtkWidget *HS_mail;
  GtkWidget *entry30;
  GtkWidget *entry31;
  GtkWidget *entry32;
  GtkWidget *label82;
  GtkWidget *label83;
  GtkWidget *label81;
  GtkWidget *label80;
  GtkObject *HS_nais_Jour_adj;
  GtkWidget *HS_nais_Jour;
  GtkObject *HS_nais_mois_adj;
  GtkWidget *HS_nais_mois;
  GtkObject *HS_nais_annee_adj;
  GtkWidget *HS_nais_annee;
  GtkWidget *HS_sexe;
  GSList *HS_sexe_group = NULL;
  GtkWidget *label84;
  GtkWidget *HS_date_recru;
  GtkWidget *hseparator1;
  GtkWidget *HS_femme;
  GtkWidget *comboboxentry3;
  GtkWidget *label85;
  GtkWidget *HS_Ajout_Agent;

  HS_Agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (HS_Agent), _("Gestion Des Agents"));

  notebook4 = gtk_notebook_new ();
  gtk_widget_show (notebook4);
  gtk_container_add (GTK_CONTAINER (HS_Agent), notebook4);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (notebook4), fixed12);

  HS_lst_agent = gtk_tree_view_new ();
  gtk_widget_show (HS_lst_agent);
  gtk_fixed_put (GTK_FIXED (fixed12), HS_lst_agent, 8, 40);
  gtk_widget_set_size_request (HS_lst_agent, 440, 232);

  label73 = gtk_label_new (_("Liste d'agents:"));
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed12), label73, 8, 8);
  gtk_widget_set_size_request (label73, 119, 17);
  gtk_misc_set_alignment (GTK_MISC (label73), 0, 0.5);

  HS_bt_ajout = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (HS_bt_ajout);
  gtk_fixed_put (GTK_FIXED (fixed12), HS_bt_ajout, 176, 280);
  gtk_widget_set_size_request (HS_bt_ajout, 78, 33);

  HS_bt_suprimer = gtk_button_new_with_mnemonic (_("Suprimer"));
  gtk_widget_show (HS_bt_suprimer);
  gtk_fixed_put (GTK_FIXED (fixed12), HS_bt_suprimer, 88, 280);
  gtk_widget_set_size_request (HS_bt_suprimer, 78, 33);

  HS_filter_affecte = gtk_check_button_new_with_mnemonic (_("Affect\303\251"));
  gtk_widget_show (HS_filter_affecte);
  gtk_fixed_put (GTK_FIXED (fixed12), HS_filter_affecte, 464, 72);
  gtk_widget_set_size_request (HS_filter_affecte, 118, 23);

  HS_filter_non_affecte = gtk_check_button_new_with_mnemonic (_("Non Affect\303\251"));
  gtk_widget_show (HS_filter_non_affecte);
  gtk_fixed_put (GTK_FIXED (fixed12), HS_filter_non_affecte, 464, 104);
  gtk_widget_set_size_request (HS_filter_non_affecte, 118, 23);

  HS_bt_status = gtk_button_new_with_mnemonic (_("Info"));
  gtk_widget_show (HS_bt_status);
  gtk_fixed_put (GTK_FIXED (fixed12), HS_bt_status, 0, 280);
  gtk_widget_set_size_request (HS_bt_status, 78, 33);

  label69 = gtk_label_new (_("Gestion Des agents"));
  gtk_widget_show (label69);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 0), label69);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (notebook4), fixed13);

  label74 = gtk_label_new_with_mnemonic (_("Ajout d'un agent:"));
  gtk_widget_show (label74);
  gtk_fixed_put (GTK_FIXED (fixed13), label74, 8, 8);
  gtk_widget_set_size_request (label74, 128, 17);
  gtk_misc_set_alignment (GTK_MISC (label74), 0, 0.5);

  label75 = gtk_label_new (_("CIN:"));
  gtk_widget_show (label75);
  gtk_fixed_put (GTK_FIXED (fixed13), label75, 8, 40);
  gtk_widget_set_size_request (label75, 49, 17);
  gtk_misc_set_alignment (GTK_MISC (label75), 0, 0.5);

  HS_cin = gtk_entry_new ();
  gtk_widget_show (HS_cin);
  gtk_fixed_put (GTK_FIXED (fixed13), HS_cin, 192, 32);
  gtk_widget_set_size_request (HS_cin, 172, 29);
  gtk_entry_set_text (GTK_ENTRY (HS_cin), _("abced"));
  gtk_entry_set_invisible_char (GTK_ENTRY (HS_cin), 8226);

  HS_nom = gtk_entry_new ();
  gtk_widget_show (HS_nom);
  gtk_fixed_put (GTK_FIXED (fixed13), HS_nom, 192, 72);
  gtk_widget_set_size_request (HS_nom, 172, 29);
  gtk_entry_set_text (GTK_ENTRY (HS_nom), _("abced"));
  gtk_entry_set_invisible_char (GTK_ENTRY (HS_nom), 8226);

  label76 = gtk_label_new (_("Nom:"));
  gtk_widget_show (label76);
  gtk_fixed_put (GTK_FIXED (fixed13), label76, 8, 80);
  gtk_widget_set_size_request (label76, 49, 17);
  gtk_misc_set_alignment (GTK_MISC (label76), 0, 0.5);

  label79 = gtk_label_new (_("Sexe:"));
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed13), label79, 8, 200);
  gtk_widget_set_size_request (label79, 49, 17);
  gtk_misc_set_alignment (GTK_MISC (label79), 0, 0.5);

  label78 = gtk_label_new (_("E-mail"));
  gtk_widget_show (label78);
  gtk_fixed_put (GTK_FIXED (fixed13), label78, 8, 160);
  gtk_widget_set_size_request (label78, 49, 17);
  gtk_misc_set_alignment (GTK_MISC (label78), 0, 0.5);

  label77 = gtk_label_new (_("Prenom:"));
  gtk_widget_show (label77);
  gtk_fixed_put (GTK_FIXED (fixed13), label77, 8, 120);
  gtk_widget_set_size_request (label77, 75, 17);
  gtk_misc_set_alignment (GTK_MISC (label77), 0, 0.5);

  HS_prenom = gtk_entry_new ();
  gtk_widget_show (HS_prenom);
  gtk_fixed_put (GTK_FIXED (fixed13), HS_prenom, 192, 112);
  gtk_widget_set_size_request (HS_prenom, 172, 29);
  gtk_entry_set_text (GTK_ENTRY (HS_prenom), _("abced"));
  gtk_entry_set_invisible_char (GTK_ENTRY (HS_prenom), 8226);

  HS_mail = gtk_entry_new ();
  gtk_widget_show (HS_mail);
  gtk_fixed_put (GTK_FIXED (fixed13), HS_mail, 192, 152);
  gtk_widget_set_size_request (HS_mail, 172, 29);
  gtk_entry_set_text (GTK_ENTRY (HS_mail), _("abced"));
  gtk_entry_set_invisible_char (GTK_ENTRY (HS_mail), 8226);

  entry30 = gtk_entry_new ();
  gtk_widget_show (entry30);
  gtk_fixed_put (GTK_FIXED (fixed13), entry30, 192, 288);
  gtk_widget_set_size_request (entry30, 172, 29);
  gtk_entry_set_text (GTK_ENTRY (entry30), _("abced"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry30), 8226);

  entry31 = gtk_entry_new ();
  gtk_widget_show (entry31);
  gtk_fixed_put (GTK_FIXED (fixed13), entry31, 192, 328);
  gtk_widget_set_size_request (entry31, 172, 29);
  gtk_entry_set_text (GTK_ENTRY (entry31), _("abced"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry31), 8226);

  entry32 = gtk_entry_new ();
  gtk_widget_show (entry32);
  gtk_fixed_put (GTK_FIXED (fixed13), entry32, 192, 408);
  gtk_widget_set_size_request (entry32, 172, 29);
  gtk_entry_set_text (GTK_ENTRY (entry32), _("abced"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry32), 8226);

  label82 = gtk_label_new (_("Lieu de naissance:"));
  gtk_widget_show (label82);
  gtk_fixed_put (GTK_FIXED (fixed13), label82, 8, 288);
  gtk_widget_set_size_request (label82, 131, 17);
  gtk_misc_set_alignment (GTK_MISC (label82), 0, 0.5);

  label83 = gtk_label_new (_("Etat civile:"));
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed13), label83, 8, 376);
  gtk_widget_set_size_request (label83, 107, 17);
  gtk_misc_set_alignment (GTK_MISC (label83), 0, 0.5);

  label81 = gtk_label_new (_("Num de compte bancaire:"));
  gtk_widget_show (label81);
  gtk_fixed_put (GTK_FIXED (fixed13), label81, 8, 336);
  gtk_widget_set_size_request (label81, 184, 17);
  gtk_misc_set_alignment (GTK_MISC (label81), 0, 0.5);

  label80 = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (label80);
  gtk_fixed_put (GTK_FIXED (fixed13), label80, 8, 240);
  gtk_widget_set_size_request (label80, 130, 17);
  gtk_misc_set_alignment (GTK_MISC (label80), 0, 0.5);

  HS_nais_Jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  HS_nais_Jour = gtk_spin_button_new (GTK_ADJUSTMENT (HS_nais_Jour_adj), 1, 0);
  gtk_widget_show (HS_nais_Jour);
  gtk_fixed_put (GTK_FIXED (fixed13), HS_nais_Jour, 192, 232);
  gtk_widget_set_size_request (HS_nais_Jour, 70, 33);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (HS_nais_Jour), TRUE);

  HS_nais_mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  HS_nais_mois = gtk_spin_button_new (GTK_ADJUSTMENT (HS_nais_mois_adj), 1, 0);
  gtk_widget_show (HS_nais_mois);
  gtk_fixed_put (GTK_FIXED (fixed13), HS_nais_mois, 272, 232);
  gtk_widget_set_size_request (HS_nais_mois, 70, 33);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (HS_nais_mois), TRUE);

  HS_nais_annee_adj = gtk_adjustment_new (2024, 2024, 2026, 1, 10, 10);
  HS_nais_annee = gtk_spin_button_new (GTK_ADJUSTMENT (HS_nais_annee_adj), 1, 0);
  gtk_widget_show (HS_nais_annee);
  gtk_fixed_put (GTK_FIXED (fixed13), HS_nais_annee, 352, 232);
  gtk_widget_set_size_request (HS_nais_annee, 70, 33);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (HS_nais_annee), TRUE);

  HS_sexe = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (HS_sexe);
  gtk_fixed_put (GTK_FIXED (fixed13), HS_sexe, 192, 192);
  gtk_widget_set_size_request (HS_sexe, 116, 23);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (HS_sexe), HS_sexe_group);
  HS_sexe_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (HS_sexe));

  label84 = gtk_label_new (_("Nombre d'enfants:"));
  gtk_widget_show (label84);
  gtk_fixed_put (GTK_FIXED (fixed13), label84, 8, 416);
  gtk_widget_set_size_request (label84, 142, 17);
  gtk_misc_set_alignment (GTK_MISC (label84), 0, 0.5);

  HS_date_recru = gtk_entry_new ();
  gtk_widget_show (HS_date_recru);
  gtk_fixed_put (GTK_FIXED (fixed13), HS_date_recru, 192, 472);
  gtk_widget_set_size_request (HS_date_recru, 172, 33);
  gtk_entry_set_invisible_char (GTK_ENTRY (HS_date_recru), 8226);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed13), hseparator1, 8, 440);
  gtk_widget_set_size_request (hseparator1, 472, 16);

  HS_femme = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (HS_femme);
  gtk_fixed_put (GTK_FIXED (fixed13), HS_femme, 320, 192);
  gtk_widget_set_size_request (HS_femme, 116, 23);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (HS_femme), HS_sexe_group);
  HS_sexe_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (HS_femme));

  comboboxentry3 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry3);
  gtk_fixed_put (GTK_FIXED (fixed13), comboboxentry3, 192, 368);
  gtk_widget_set_size_request (comboboxentry3, 205, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), "Celibataire");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), "Mari\303\251(e)");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), "Veuf/Veuve");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), "Divorc\303\251(e)");

  label85 = gtk_label_new (_("Mot de passe:"));
  gtk_widget_show (label85);
  gtk_fixed_put (GTK_FIXED (fixed13), label85, 8, 480);
  gtk_widget_set_size_request (label85, 129, 17);
  gtk_misc_set_alignment (GTK_MISC (label85), 0, 0.5);

  HS_Ajout_Agent = gtk_label_new (_("Ajout Agent"));
  gtk_widget_show (HS_Ajout_Agent);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 1), HS_Ajout_Agent);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (HS_Agent, HS_Agent, "HS_Agent");
  GLADE_HOOKUP_OBJECT (HS_Agent, notebook4, "notebook4");
  GLADE_HOOKUP_OBJECT (HS_Agent, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (HS_Agent, HS_lst_agent, "HS_lst_agent");
  GLADE_HOOKUP_OBJECT (HS_Agent, label73, "label73");
  GLADE_HOOKUP_OBJECT (HS_Agent, HS_bt_ajout, "HS_bt_ajout");
  GLADE_HOOKUP_OBJECT (HS_Agent, HS_bt_suprimer, "HS_bt_suprimer");
  GLADE_HOOKUP_OBJECT (HS_Agent, HS_filter_affecte, "HS_filter_affecte");
  GLADE_HOOKUP_OBJECT (HS_Agent, HS_filter_non_affecte, "HS_filter_non_affecte");
  GLADE_HOOKUP_OBJECT (HS_Agent, HS_bt_status, "HS_bt_status");
  GLADE_HOOKUP_OBJECT (HS_Agent, label69, "label69");
  GLADE_HOOKUP_OBJECT (HS_Agent, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (HS_Agent, label74, "label74");
  GLADE_HOOKUP_OBJECT (HS_Agent, label75, "label75");
  GLADE_HOOKUP_OBJECT (HS_Agent, HS_cin, "HS_cin");
  GLADE_HOOKUP_OBJECT (HS_Agent, HS_nom, "HS_nom");
  GLADE_HOOKUP_OBJECT (HS_Agent, label76, "label76");
  GLADE_HOOKUP_OBJECT (HS_Agent, label79, "label79");
  GLADE_HOOKUP_OBJECT (HS_Agent, label78, "label78");
  GLADE_HOOKUP_OBJECT (HS_Agent, label77, "label77");
  GLADE_HOOKUP_OBJECT (HS_Agent, HS_prenom, "HS_prenom");
  GLADE_HOOKUP_OBJECT (HS_Agent, HS_mail, "HS_mail");
  GLADE_HOOKUP_OBJECT (HS_Agent, entry30, "entry30");
  GLADE_HOOKUP_OBJECT (HS_Agent, entry31, "entry31");
  GLADE_HOOKUP_OBJECT (HS_Agent, entry32, "entry32");
  GLADE_HOOKUP_OBJECT (HS_Agent, label82, "label82");
  GLADE_HOOKUP_OBJECT (HS_Agent, label83, "label83");
  GLADE_HOOKUP_OBJECT (HS_Agent, label81, "label81");
  GLADE_HOOKUP_OBJECT (HS_Agent, label80, "label80");
  GLADE_HOOKUP_OBJECT (HS_Agent, HS_nais_Jour, "HS_nais_Jour");
  GLADE_HOOKUP_OBJECT (HS_Agent, HS_nais_mois, "HS_nais_mois");
  GLADE_HOOKUP_OBJECT (HS_Agent, HS_nais_annee, "HS_nais_annee");
  GLADE_HOOKUP_OBJECT (HS_Agent, HS_sexe, "HS_sexe");
  GLADE_HOOKUP_OBJECT (HS_Agent, label84, "label84");
  GLADE_HOOKUP_OBJECT (HS_Agent, HS_date_recru, "HS_date_recru");
  GLADE_HOOKUP_OBJECT (HS_Agent, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (HS_Agent, HS_femme, "HS_femme");
  GLADE_HOOKUP_OBJECT (HS_Agent, comboboxentry3, "comboboxentry3");
  GLADE_HOOKUP_OBJECT (HS_Agent, label85, "label85");
  GLADE_HOOKUP_OBJECT (HS_Agent, HS_Ajout_Agent, "HS_Ajout_Agent");

  return HS_Agent;
}

GtkWidget*
create_Auth (void)
{
  GtkWidget *Auth;
  GtkWidget *fixed14;
  GtkWidget *label87;
  GtkWidget *HS_auth_cin;
  GtkWidget *label88;
  GtkWidget *HS_auth_mdp;
  GtkWidget *label86;
  GtkWidget *HS_auth_valider;

  Auth = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Auth), _("Authentification"));

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (Auth), fixed14);

  label87 = gtk_label_new (_("CIN:"));
  gtk_widget_show (label87);
  gtk_fixed_put (GTK_FIXED (fixed14), label87, 24, 80);
  gtk_widget_set_size_request (label87, 49, 17);
  gtk_misc_set_alignment (GTK_MISC (label87), 0, 0.5);

  HS_auth_cin = gtk_entry_new ();
  gtk_widget_show (HS_auth_cin);
  gtk_fixed_put (GTK_FIXED (fixed14), HS_auth_cin, 160, 72);
  gtk_widget_set_size_request (HS_auth_cin, 172, 33);
  gtk_entry_set_invisible_char (GTK_ENTRY (HS_auth_cin), 8226);

  label88 = gtk_label_new (_("Mot de passe:"));
  gtk_widget_show (label88);
  gtk_fixed_put (GTK_FIXED (fixed14), label88, 24, 136);
  gtk_widget_set_size_request (label88, 100, 17);
  gtk_misc_set_alignment (GTK_MISC (label88), 0, 0.5);

  HS_auth_mdp = gtk_entry_new ();
  gtk_widget_show (HS_auth_mdp);
  gtk_fixed_put (GTK_FIXED (fixed14), HS_auth_mdp, 160, 128);
  gtk_widget_set_size_request (HS_auth_mdp, 172, 33);
  gtk_entry_set_invisible_char (GTK_ENTRY (HS_auth_mdp), 8226);

  label86 = gtk_label_new (_("Connecter-vous"));
  gtk_widget_show (label86);
  gtk_fixed_put (GTK_FIXED (fixed14), label86, 152, 16);
  gtk_widget_set_size_request (label86, 112, 16);
  gtk_misc_set_alignment (GTK_MISC (label86), 0, 0.5);

  HS_auth_valider = gtk_button_new_with_mnemonic (_("Connecter"));
  gtk_widget_show (HS_auth_valider);
  gtk_fixed_put (GTK_FIXED (fixed14), HS_auth_valider, 160, 192);
  gtk_widget_set_size_request (HS_auth_valider, 85, 33);

  g_signal_connect ((gpointer) HS_auth_valider, "clicked",
                    G_CALLBACK (on_HS_auth_valider_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Auth, Auth, "Auth");
  GLADE_HOOKUP_OBJECT (Auth, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (Auth, label87, "label87");
  GLADE_HOOKUP_OBJECT (Auth, HS_auth_cin, "HS_auth_cin");
  GLADE_HOOKUP_OBJECT (Auth, label88, "label88");
  GLADE_HOOKUP_OBJECT (Auth, HS_auth_mdp, "HS_auth_mdp");
  GLADE_HOOKUP_OBJECT (Auth, label86, "label86");
  GLADE_HOOKUP_OBJECT (Auth, HS_auth_valider, "HS_auth_valider");

  return Auth;
}

GtkWidget*
create_MF_Reclamation (void)
{
  GtkWidget *MF_Reclamation;
  GtkWidget *fixed15;
  GtkWidget *MF_cin;
  GtkWidget *label89;
  GtkWidget *MF_num_place;
  GtkWidget *MF_calendrier;
  GtkWidget *MF_remarque;
  GtkWidget *label90;
  GtkWidget *label91;
  GtkWidget *label92;
  GtkWidget *MF_Reclamation_tree;
  GtkWidget *MF_description;
  GtkWidget *MF_Avis_tree;
  GtkObject *MF_Note_adj;
  GtkWidget *MF_Note;
  GtkWidget *label93;
  GtkWidget *radiobutton5;
  GSList *radiobutton5_group = NULL;
  GtkWidget *label94;
  GtkWidget *label95;
  GtkWidget *label96;
  GtkWidget *label97;
  GtkWidget *label98;
  GtkWidget *MF_mal_gare;
  GtkWidget *MF_non_dispo;
  GtkWidget *MF_prob_paiement;
  GtkWidget *MF_securite;
  GtkWidget *MF_autre;
  GtkWidget *MF_piece_jointe;
  GtkWidget *MF_valider_cin;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label109;
  GtkWidget *MF_valider_reclamation;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label101;
  GtkWidget *MF_reset_form;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label100;
  GtkWidget *MF_Ajouter_reclamtion;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label107;
  GtkWidget *MF_modifier_reclamation;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label106;
  GtkWidget *MF_supp_reclamation;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label105;
  GtkWidget *MF_service_rating;
  GSList *MF_service_rating_group = NULL;
  GtkWidget *radiobutton4;
  GtkWidget *MF_Ajouter_avis;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label102;
  GtkWidget *MF_modifier_avis;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label103;
  GtkWidget *MF_supprimer_avis;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label104;
  GtkWidget *MF_filtre_avis;

  MF_Reclamation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MF_Reclamation), _("Reclamation"));

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (MF_Reclamation), fixed15);

  MF_cin = gtk_entry_new ();
  gtk_widget_show (MF_cin);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_cin, 160, 16);
  gtk_widget_set_size_request (MF_cin, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (MF_cin), 8226);

  label89 = gtk_label_new (_("Type de r\303\251clamation "));
  gtk_widget_show (label89);
  gtk_fixed_put (GTK_FIXED (fixed15), label89, 0, 64);
  gtk_widget_set_size_request (label89, 192, 32);

  MF_num_place = gtk_entry_new ();
  gtk_widget_show (MF_num_place);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_num_place, 200, 232);
  gtk_widget_set_size_request (MF_num_place, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (MF_num_place), 8226);

  MF_calendrier = gtk_calendar_new ();
  gtk_widget_show (MF_calendrier);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_calendrier, 16, 296);
  gtk_widget_set_size_request (MF_calendrier, 208, 160);
  gtk_calendar_display_options (GTK_CALENDAR (MF_calendrier),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  MF_remarque = gtk_entry_new ();
  gtk_widget_show (MF_remarque);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_remarque, 152, 488);
  gtk_widget_set_size_request (MF_remarque, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (MF_remarque), 8226);

  label90 = gtk_label_new (_("Pi\303\251ce jointe ( Facultatif ) "));
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (fixed15), label90, 0, 464);
  gtk_widget_set_size_request (label90, 200, 16);

  label91 = gtk_label_new (_("Remarque \303\240 ajouter "));
  gtk_widget_show (label91);
  gtk_fixed_put (GTK_FIXED (fixed15), label91, 0, 488);
  gtk_widget_set_size_request (label91, 168, 24);

  label92 = gtk_label_new (_("Entrer votre CIN"));
  gtk_widget_show (label92);
  gtk_fixed_put (GTK_FIXED (fixed15), label92, 8, 24);
  gtk_widget_set_size_request (label92, 152, 16);

  MF_Reclamation_tree = gtk_tree_view_new ();
  gtk_widget_show (MF_Reclamation_tree);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_Reclamation_tree, 528, 8);
  gtk_widget_set_size_request (MF_Reclamation_tree, 384, 144);

  MF_description = gtk_entry_new ();
  gtk_widget_show (MF_description);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_description, 704, 240);
  gtk_widget_set_size_request (MF_description, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (MF_description), 8226);

  MF_Avis_tree = gtk_tree_view_new ();
  gtk_widget_show (MF_Avis_tree);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_Avis_tree, 520, 304);
  gtk_widget_set_size_request (MF_Avis_tree, 392, 168);

  MF_Note_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  MF_Note = gtk_spin_button_new (GTK_ADJUSTMENT (MF_Note_adj), 1, 0);
  gtk_widget_show (MF_Note);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_Note, 568, 272);
  gtk_widget_set_size_request (MF_Note, 60, 27);

  label93 = gtk_label_new (_("Notre service"));
  gtk_widget_show (label93);
  gtk_fixed_put (GTK_FIXED (fixed15), label93, 512, 208);
  gtk_widget_set_size_request (label93, 120, 24);

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("Tr\303\251s bien"));
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed15), radiobutton5, 832, 208);
  gtk_widget_set_size_request (radiobutton5, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton5_group);
  radiobutton5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  label94 = gtk_label_new (_("Description de votre avis "));
  gtk_widget_show (label94);
  gtk_fixed_put (GTK_FIXED (fixed15), label94, 512, 240);
  gtk_widget_set_size_request (label94, 192, 24);

  label95 = gtk_label_new (_("Note "));
  gtk_widget_show (label95);
  gtk_fixed_put (GTK_FIXED (fixed15), label95, 472, 264);
  gtk_widget_set_size_request (label95, 88, 40);
  gtk_misc_set_alignment (GTK_MISC (label95), 1, 0.53);

  label96 = gtk_label_new (_("Trier par note "));
  gtk_widget_show (label96);
  gtk_fixed_put (GTK_FIXED (fixed15), label96, 512, 528);
  gtk_widget_set_size_request (label96, 120, 32);

  label97 = gtk_label_new (_("Date  de l'incident "));
  gtk_widget_show (label97);
  gtk_fixed_put (GTK_FIXED (fixed15), label97, 0, 248);
  gtk_widget_set_size_request (label97, 160, 56);

  label98 = gtk_label_new (_("Num\303\251ro de place parking"));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed15), label98, 0, 232);
  gtk_widget_set_size_request (label98, 208, 24);

  MF_mal_gare = gtk_check_button_new_with_mnemonic (_("V\303\251hicule mal gar\303\251 "));
  gtk_widget_show (MF_mal_gare);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_mal_gare, 48, 96);
  gtk_widget_set_size_request (MF_mal_gare, 168, 40);

  MF_non_dispo = gtk_check_button_new_with_mnemonic (_("Place non disponible "));
  gtk_widget_show (MF_non_dispo);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_non_dispo, 48, 152);
  gtk_widget_set_size_request (MF_non_dispo, 176, 24);

  MF_prob_paiement = gtk_check_button_new_with_mnemonic (_("Probl\303\251me de paiement"));
  gtk_widget_show (MF_prob_paiement);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_prob_paiement, 48, 128);
  gtk_widget_set_size_request (MF_prob_paiement, 200, 24);

  MF_securite = gtk_check_button_new_with_mnemonic (_("S\303\251curit\303\251 de v\303\251hicule"));
  gtk_widget_show (MF_securite);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_securite, 48, 176);
  gtk_widget_set_size_request (MF_securite, 176, 24);

  MF_autre = gtk_check_button_new_with_mnemonic (_("Autre"));
  gtk_widget_show (MF_autre);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_autre, 48, 200);
  gtk_widget_set_size_request (MF_autre, 118, 24);

  MF_piece_jointe = gtk_file_chooser_button_new (_("Select a File"), GTK_FILE_CHOOSER_ACTION_OPEN);
  gtk_widget_show (MF_piece_jointe);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_piece_jointe, 192, 456);
  gtk_widget_set_size_request (MF_piece_jointe, 66, 29);

  MF_valider_cin = gtk_button_new ();
  gtk_widget_show (MF_valider_cin);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_valider_cin, 344, 16);
  gtk_widget_set_size_request (MF_valider_cin, 104, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (MF_valider_cin), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label109 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label109);
  gtk_box_pack_start (GTK_BOX (hbox13), label109, FALSE, FALSE, 0);

  MF_valider_reclamation = gtk_button_new ();
  gtk_widget_show (MF_valider_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_valider_reclamation, 40, 536);
  gtk_widget_set_size_request (MF_valider_reclamation, 104, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (MF_valider_reclamation), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label101 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label101);
  gtk_box_pack_start (GTK_BOX (hbox6), label101, FALSE, FALSE, 0);

  MF_reset_form = gtk_button_new ();
  gtk_widget_show (MF_reset_form);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_reset_form, 152, 536);
  gtk_widget_set_size_request (MF_reset_form, 184, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (MF_reset_form), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label100 = gtk_label_new_with_mnemonic (_("Effacer le formulaire "));
  gtk_widget_show (label100);
  gtk_box_pack_start (GTK_BOX (hbox5), label100, FALSE, FALSE, 0);

  MF_Ajouter_reclamtion = gtk_button_new ();
  gtk_widget_show (MF_Ajouter_reclamtion);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_Ajouter_reclamtion, 528, 160);
  gtk_widget_set_size_request (MF_Ajouter_reclamtion, 104, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (MF_Ajouter_reclamtion), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label107 = gtk_label_new_with_mnemonic (_("Ajouter "));
  gtk_widget_show (label107);
  gtk_box_pack_start (GTK_BOX (hbox12), label107, FALSE, FALSE, 0);

  MF_modifier_reclamation = gtk_button_new ();
  gtk_widget_show (MF_modifier_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_modifier_reclamation, 632, 160);
  gtk_widget_set_size_request (MF_modifier_reclamation, 112, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (MF_modifier_reclamation), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label106 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label106);
  gtk_box_pack_start (GTK_BOX (hbox11), label106, FALSE, FALSE, 0);

  MF_supp_reclamation = gtk_button_new ();
  gtk_widget_show (MF_supp_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_supp_reclamation, 744, 160);
  gtk_widget_set_size_request (MF_supp_reclamation, 120, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (MF_supp_reclamation), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label105 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label105);
  gtk_box_pack_start (GTK_BOX (hbox10), label105, FALSE, FALSE, 0);

  MF_service_rating = gtk_radio_button_new_with_mnemonic (NULL, _("Acceptable"));
  gtk_widget_show (MF_service_rating);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_service_rating, 624, 208);
  gtk_widget_set_size_request (MF_service_rating, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (MF_service_rating), MF_service_rating_group);
  MF_service_rating_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (MF_service_rating));

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("Mauvais"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed15), radiobutton4, 736, 208);
  gtk_widget_set_size_request (radiobutton4, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), MF_service_rating_group);
  MF_service_rating_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  MF_Ajouter_avis = gtk_button_new ();
  gtk_widget_show (MF_Ajouter_avis);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_Ajouter_avis, 520, 480);
  gtk_widget_set_size_request (MF_Ajouter_avis, 96, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (MF_Ajouter_avis), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label102 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label102);
  gtk_box_pack_start (GTK_BOX (hbox7), label102, FALSE, FALSE, 0);

  MF_modifier_avis = gtk_button_new ();
  gtk_widget_show (MF_modifier_avis);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_modifier_avis, 616, 480);
  gtk_widget_set_size_request (MF_modifier_avis, 104, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (MF_modifier_avis), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label103 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label103);
  gtk_box_pack_start (GTK_BOX (hbox8), label103, FALSE, FALSE, 0);

  MF_supprimer_avis = gtk_button_new ();
  gtk_widget_show (MF_supprimer_avis);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_supprimer_avis, 720, 480);
  gtk_widget_set_size_request (MF_supprimer_avis, 128, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (MF_supprimer_avis), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label104 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label104);
  gtk_box_pack_start (GTK_BOX (hbox9), label104, FALSE, FALSE, 0);

  MF_filtre_avis = gtk_combo_box_entry_new_text ();
  gtk_widget_show (MF_filtre_avis);
  gtk_fixed_put (GTK_FIXED (fixed15), MF_filtre_avis, 624, 528);
  gtk_widget_set_size_request (MF_filtre_avis, 189, 29);

  g_signal_connect ((gpointer) MF_valider_cin, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) MF_valider_reclamation, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) MF_reset_form, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) MF_Ajouter_reclamtion, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) MF_modifier_reclamation, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) MF_supp_reclamation, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);
  g_signal_connect ((gpointer) MF_Ajouter_avis, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) MF_modifier_avis, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MF_Reclamation, MF_Reclamation, "MF_Reclamation");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_cin, "MF_cin");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, label89, "label89");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_num_place, "MF_num_place");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_calendrier, "MF_calendrier");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_remarque, "MF_remarque");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, label90, "label90");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, label91, "label91");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, label92, "label92");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_Reclamation_tree, "MF_Reclamation_tree");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_description, "MF_description");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_Avis_tree, "MF_Avis_tree");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_Note, "MF_Note");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, label93, "label93");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, label94, "label94");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, label95, "label95");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, label96, "label96");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, label97, "label97");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, label98, "label98");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_mal_gare, "MF_mal_gare");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_non_dispo, "MF_non_dispo");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_prob_paiement, "MF_prob_paiement");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_securite, "MF_securite");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_autre, "MF_autre");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_piece_jointe, "MF_piece_jointe");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_valider_cin, "MF_valider_cin");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, image13, "image13");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, label109, "label109");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_valider_reclamation, "MF_valider_reclamation");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, image6, "image6");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, label101, "label101");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_reset_form, "MF_reset_form");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, image5, "image5");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, label100, "label100");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_Ajouter_reclamtion, "MF_Ajouter_reclamtion");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, image12, "image12");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, label107, "label107");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_modifier_reclamation, "MF_modifier_reclamation");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, image11, "image11");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, label106, "label106");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_supp_reclamation, "MF_supp_reclamation");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, image10, "image10");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, label105, "label105");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_service_rating, "MF_service_rating");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_Ajouter_avis, "MF_Ajouter_avis");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, image7, "image7");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, label102, "label102");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_modifier_avis, "MF_modifier_avis");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, image8, "image8");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, label103, "label103");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_supprimer_avis, "MF_supprimer_avis");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, image9, "image9");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, label104, "label104");
  GLADE_HOOKUP_OBJECT (MF_Reclamation, MF_filtre_avis, "MF_filtre_avis");

  return MF_Reclamation;
}

